pipeline {
    agent any
    parameters {
        string(name: 'DOCKER_IMAGE', defaultValue: 'my-java-app', description: 'Docker image name')
        string(name: 'DOCKER_TAG', defaultValue: 'latest', description: 'Docker image tag')
    }
    environment {
        BOUNDS = bounds(1, 100)
    }
    stages {
        stage('Build Jar') {
            steps {
                sh 'javac Main.java'
                sh 'jar cf app.jar Main.class'
            }
        }
        stage('Build & Push Docker') {
            parallel {
                stage('Build Docker') {
                    steps {
                        sh 'docker build -t ${params.DOCKER_IMAGE}:${params.DOCKER_TAG} .'
                    }
                }
                stage('Docker Login & Push') {
                    steps {
                        sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                        sh 'docker push ${params.DOCKER_IMAGE}:${params.DOCKER_TAG}'
                    }
                }
            }
        }
    }
    post {
        always {
            sh 'docker rmi ${params.DOCKER_IMAGE}:${params.DOCKER_TAG} || true'
            sh 'rm -f Main.class app.jar'
        }
    }
}
library identifier: 'sharedlib', retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://your-sharedlib-repo.git'
])
